#version: "3"
services:
  clientemqtt:
    image: ejer_mqtt
    container_name: mqtt_service
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - SERVIDOR=${SERVIDOR}
      - TOPICO_1=${TOPICO_1}
      - TOPICO_2=${TOPICO_2}
      - TOPICO_PUBLICA=${TOPICO_PUBLICA}
    restart: unless-stopped
